### ISSUE TITLE
 Pruebas de aceptación: Gestión 5º Ingeniería Informática

### ISSUE THREAD

**Issue by dzg0013** [dzg0013/GESPRO_PracticaGestionCodigo#2]
He utilizado la aplicación para gestionar los trabajos fin de carrera de la asignatura a extinguir de Ingeniería Informática
El problema es que cuando pongo las páginas en la web (http:) y no en local (C:/) no se muestra ni el calendario de Google ni el gráfico generado con el API de Google .
Ver https://dl.dropboxusercontent.com/u/18996787/web/HistoricoSist.html y https://dl.dropboxusercontent.com/u/18996787/web/index.html

**Comment by dsv0010** [comment]
Según la consola del navegador, te faltan algunos javascripts por cargar. 

Y son ./js/materialize.min.js, ./js/init.js y ./js/chart.

![imagen](https://cloud.githubusercontent.com/assets/23051780/20482570/9a8a34f8-afed-11e6-8514-806ba2c6d3f6.png)


El chart.js es el que carga las gráficas.

El problema del calendario parece ser problema de la url, usé google shorter porque con la URL entera no pasaba el estándar de HTML5

   -  URL: https://www.google.com/calendar/embed?src=ubutfgm%40gmail.com&ctz=Europe/Madrid

  -  Cambiando http://goo.gl/PgEkF1 por //goo.gl/PgEkF1 te carga el calendario, pero parece que no los eventos...

**Comment by dzg0013** [comment]
Todo funciona ahora. Gracias Beatriz. En esta página esta el despliegue de la aplicación el un contexto de uso de la titulación a extinguir de Ingeniería Informática. Se ha notificado a los participantes de la asignatura la nueva actualización y si detectan algún bug que me informen.

**Comment by dsv0010** [comment]
Acabo de meterme y en la página principal he detectado un pequeño error: las especificaciones de entrega y los links de documentos son iguales, imagino que habrás cambiado algún fichero CSV y lo has cambiado con el nombre que no era...

**Comment by dzg0013** [comment]
Gracias Beatriz por el chequeo. Ya lo he corregido. Además he añadido una nueva propiedad para gestionar la url del calendario sin tener que compilar la aplicación.
Me ha quedado una duda a la hora de generar la gráfica del histórico porque no aparecen las estadísticas del curso 2013-14 ???

**Comment by dsv0010** [comment]
Había un fallo en el código, pero ¡ya está solucionado!

La verdad me tendría que haber dado cuenta porque es bastante visible, pero yo solía comprobar los primeros años y si los primeros estaban bien suponía que los de abajo también...

**Comment by dzg0013** [comment]
Gracias de nuevo Beatriz.
He observado tu commit y queda muy clara tu solución en el códido.
Este error es un clásico. Además es muy simple pero por mucho que se explique (técnica de pruebas de valores límite), le repetiremos una y otra vez. Lo interesante es saber dectarlo y corregirlo.
