### ISSUE TITLE
Simulación de un sistema de control de versiones

### ISSUE THREAD

**Issue by dzg0013** [dzg0013/GESPRO_PracticaGestionCodigo#3]
Este issue es para los commints que no tienen ningun issue asociado.

**Comment by dsv0010** [comment]
El  código del commit f1ce23b del proyecto de Beatriz, no se puede realizar, ya que no existe el archivo a eliminar.

https://bitbucket.org/ubu_tfg/2014-beatriz/commits/1c22bb7335568ac3a5f7716fd2ac4e87e9c8f694
